name: ra_example
description: A starting point for Dart libraries or applications.
version: 0.7.5-pre
publish_to: 'none'

environment:
  sdk: ^3.2.3

dependencies:
  drift: ^2.15.0
  essential_xlsx: ^2.0.0
  meta: ^1.14.0
  ra:
    path: ../
  token_bucket: ^0.9.7-pre

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
