name: ra
description: A starting point for Dart libraries or applications.
version: 0.7.5-pre

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.11.0
  shelf: ^1.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
